function   [Cluster_element,Mean] = Mean_shift(Feature,radius)
  % This is a mean shift, generated by Meng Yu from HIT.
  % Feature are the most concerns
  

 Cluster_element = {};
 Cluster = 0;s = 0;Mean = []; 
 while size(Feature,2) > 3
      s = s +1
  mu = Feature(:,1);
   
  delta = 10;
  
  while(delta>0.001)
      k = 0.00000
      KP_MU = [];
      pool = [];
      for  i = 1 : size(Feature,2)
          K = flat_kernel(Feature(:,i),mu,radius);
          if K ==1
              KP_MU = [KP_MU,Feature(:,i)];
              k = k + 1;        
          end
      end
      KP_sum = sum(KP_MU,2);
      mu_improve = KP_sum/k;
      delta = norm(mu - mu_improve);
      mu = mu_improve;
  end
  
  % After mean is selected we should delete the clustered terms.
      K_pool = [];
  Cluster = Cluster + 1;
  for i = 1 : size(Feature,2)
      K = flat_kernel(Feature(:,i),mu,radius);
    if K ==1
      K_pool = [K_pool,i];       
    end
  end

Cluster_element{Cluster} = Feature(:,K_pool);
Feature(:,K_pool) = [];
Mean = [Mean,mu];

end
